server:
  port: 8080

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui-custom.html
  swagger-ui.operationsSorter: method

  mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:/mapper/*.xml

# Flyway 설정 추가하기
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

# 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트 노출
  endpoint:
    prometheus:
      enabled: true  # Prometheus 엔드포인트 활성화
